### ISSUE TITLE
Error: Invalid base32 character in key

### ISSUE THREAD

**Issue by siyasangab** [bellstrand/totp-generator#134]
Hi

Thanks for sharing this library with community!

I am running into an issue though when my key has the equals '=' char. From the docs it says '=' is acceptable:

```
{ key: 'H73TG4DV24=X=OHQYBWRPTRT5BB4=L7T' }
 ⨯ Error: Invalid base32 character in key
    at TOTP.base32tohex (webpack-internal:///(rsc)/./node_modules/totp-generator/lib/esm/index.js:45:35)
    at TOTP.generate (webpack-internal:///(rsc)/./node_modules/totp-generator/lib/esm/index.js:19:32)
    at GET (webpack-internal:///(rsc)/./src/app/api/otp/route.ts:28:79)
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:63815
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\trace\tracer.js:133:36
    at NoopContextManager.with (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
    at ContextAPI.with (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)      
    at NoopTracer.startActiveSpan (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18093)
    at ProxyTracer.startActiveSpan (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18854)
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\trace\tracer.js:122:103
    at NoopContextManager.with (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
    at ContextAPI.with (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)      
    at NextTracerImpl.trace (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\trace\tracer.js:122:28)
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:56866
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:37102)
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54639
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:36351)
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54601
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eU.execute (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53994)
    at eU.handle (C:\stuff\qoutequests.v3\web\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:65073) 
    at doRender (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:1333:60)
    at cacheEntry.responseCache.get.routeKind (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:1555:34)
    at ResponseCache.get (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\response-cache\index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:1463:53)
    at C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:992:121
    at NextTracerImpl.trace (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\trace\tracer.js:104:20)
    at DevServer.renderToResponseWithComponents (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:992:41)
    at DevServer.renderPageComponent (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:1856:35)     
    at async DevServer.renderToResponseImpl (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:1894:32)
    at async DevServer.pipeImpl (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\next-server.js:271:17)
    at async DevServer.handleRequestImpl (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\base-server.js:807:17)  
    at async C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\dev\next-dev-server.js:331:20
    at async Span.traceAsyncFn (C:\stuff\qoutequests.v3\web\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
    at async invokeRender (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\router-server.js:163:21)
    at async handleRequest (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\router-server.js:342:24)
    at async requestHandlerImpl (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\router-server.js:366:13)     
    at async Server.requestListener (C:\stuff\qoutequests.v3\web\node_modules\next\dist\server\lib\start-server.js:140:13) 
``` 

It doesn't matter the count of the '=', this key also results in the same error: QHQGOSBVK2J=OJYC7LB4UJLG6HF72IEV

**Comment by bellstrand** [comment]
@siyasangab `=` is only allowed to be used as a padding character, ie in the end of the key.
Having it somewhere else would result in an incorrect value since the base32 string can only have 32 valid characters, in this case `a-z  2-7`.

What's your use case when you end up with `=` in the key?

**Comment by siyasangab** [comment]
Thank you everyone!
